import math
a =float(input("Escoge un valor para a: "))
print(a)
b =float(input("Escoge un valor para b: "))
print(b)
c =float(input("Escoge un valor para c: "))
print(c)
step1=(float(b)*float(b))
step2=(4*float(a)*float(c))
step3=(step1-step2)
step4=math.sqrt(step3)
x1=(-b-step4)/(2*a)
x2=(-b+step4)/(2*a)
print("x1:",(x1))
print("x2:",(x2))